name: Cek Website Unpam

on:
  schedule:
    # --- JADWAL WEEKDAYS (SENIN - JUMAT) ---
    
    # 1. Jam Kerja Aktif (07:00 - 17:00 WIB)
    # Konversi UTC: 00:00 - 10:00
    # Frekuensi: Tiap 15 menit
    - cron: '*/15 0-10 * * 1-5'

    # 2. Sisa Waktu Weekdays (Malam Hari)
    # Sisa waktu setelah jam 17:00 WIB.
    # Kita set cek di jam 19:00 WIB (12:00 UTC) dan 01:00 WIB (18:00 UTC)
    - cron: '0 12,18 * * 1-5'

    # --- JADWAL WEEKEND (SABTU - MINGGU) ---
    
    # 3. Full Day Weekend
    # Frekuensi: Tiap 6 jam (Jam 0, 6, 12, 18 UTC)
    # Sama dengan: Jam 07:00, 13:00, 19:00, 01:00 WIB
    - cron: '0 0,6,12,18 * * 6,0'

  workflow_dispatch:
  
jobs:
  check_website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Cache state file agar hash tersimpan antar-run
    # - name: Cache state
    # id: cache-state
    #  uses: actions/cache@v3
    #  with:
    #   path: page_hash.txt
    #    key: website-state-${{ github.run_id }}
    #    restore-keys: |
    #      website-state-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main.py
    
    - name: Commit and push changes if hash changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add page_hash.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update page hash" && git push)
        
